// Realistic placeholder catalog data for JaneDeraa.
// Image URLs point at picsum.photos (free placeholder photo service) — the
// seed script downloads each one and re-uploads it into Supabase Storage, so
// the product rows end up pointing at your own bucket, not a third party.
// Swap these for real product photography whenever it's ready.

const picsum = (seed, w, h) => `https://picsum.photos/seed/${seed}/${w}/${h}`;

const CATEGORIES = [
  { slug: 'women-coats', name: 'Coats', gender: 'women', description: 'Outerwear cut from wool, cashmere and cotton gabardine.' },
  { slug: 'women-tailoring', name: 'Tailoring', gender: 'women', description: 'Blazers, suiting and trousers cut close to the body.' },
  { slug: 'women-knitwear', name: 'Knitwear', gender: 'women', description: 'Merino and cashmere knits in a quiet palette.' },
  { slug: 'women-shirting', name: 'Shirting', gender: 'women', description: 'Silk and cotton shirting for everyday and evening.' },
  { slug: 'men-coats', name: 'Coats', gender: 'men', description: 'Overcoats and trenches built to outlast the season.' },
  { slug: 'men-tailoring', name: 'Tailoring', gender: 'men', description: 'Suits and trousers cut from the house pattern block.' },
  { slug: 'men-knitwear', name: 'Knitwear', gender: 'men', description: 'Cashmere and merino knitwear, fully fashioned.' },
  { slug: 'men-shirting', name: 'Shirting', gender: 'men', description: 'Oxford, poplin and linen shirting.' },
  { slug: 'custom-made', name: 'Custom-Made', gender: 'unisex', description: 'House patterns adjusted to your proportions.' },
  { slug: 'bespoke', name: 'Bespoke', gender: 'unisex', description: 'Cut from nothing but your own measurements.' },
];

const COLOR_SETS = {
  neutral: [
    { name: 'Ivory', hex: '#EDE8E0' },
    { name: 'Stone', hex: '#B7B7B7' },
    { name: 'Espresso', hex: '#3B2E27' },
    { name: 'Charcoal', hex: '#2A2A28' },
  ],
  warm: [
    { name: 'Camel', hex: '#B79465' },
    { name: 'Espresso', hex: '#3B2E27' },
    { name: 'Forest', hex: '#1D4429' },
    { name: 'Ivory', hex: '#EDE8E0' },
  ],
  evening: [
    { name: 'Black', hex: '#111110' },
    { name: 'Deep Green', hex: '#1D4429' },
    { name: 'Espresso', hex: '#3B2E27' },
  ],
};

const RTW_SIZES = ['XS', 'S', 'M', 'L', 'XL'];
const MADE_TO_MEASURE = ['Made to measure'];

function product({
  slug,
  name,
  category,
  gender,
  tier,
  price,
  short,
  description,
  fabric,
  care,
  sizes,
  colors,
  tags = [],
  featured = false,
  imageCount = 3,
  images, // optional: explicit list of http(s) URLs or local paths (see uploadImage in seed.js), overrides the picsum auto-generation
}) {
  return {
    slug,
    name,
    category,
    gender,
    tier,
    price_cents: Math.round(price * 100),
    currency: 'USD',
    short_description: short,
    description,
    fabric,
    care,
    sizes,
    colors,
    tags,
    is_featured: featured,
    in_stock: true,
    sourceImages:
      images || Array.from({ length: imageCount }, (_, i) => picsum(`jd-${slug}-${i}`, 900, i === 0 ? 1125 : 1000)),
  };
}

const PRODUCTS = [
  // ---- Women — Ready-to-wear ----
  product({
    slug: 'wool-flannel-overcoat',
    name: 'Wool Flannel Overcoat',
    category: 'women-coats',
    gender: 'women',
    tier: 'ready-to-wear',
    price: 1890,
    short: 'A single-breasted overcoat cut from heavyweight Italian flannel.',
    description:
      'Cut from an heavyweight Italian flannel milled in Biella, this overcoat sits close through the shoulder and falls straight to below the knee. Horn buttons, a full canvas front, and a back vent for movement.',
    fabric: '100% wool flannel, Biella, Italy. Cupro lining.',
    care: 'Dry clean only. Store on a broad-shouldered hanger.',
    sizes: RTW_SIZES,
    colors: COLOR_SETS.neutral,
    tags: ['New'],
    featured: true,
  }),
  product({
    slug: 'cashmere-wrap-coat',
    name: 'Cashmere Wrap Coat',
    category: 'women-coats',
    gender: 'women',
    tier: 'ready-to-wear',
    price: 2450,
    short: 'An unstructured wrap coat in double-faced cashmere.',
    description:
      'Double-faced cashmere with no visible seams, tied with a self-belt rather than buttoned. Deep patch pockets, raglan sleeves, and a fall that skims rather than clings.',
    fabric: '100% double-faced cashmere, Mongolia.',
    care: 'Dry clean only.',
    sizes: RTW_SIZES,
    colors: COLOR_SETS.warm,
    tags: ['Limited'],
  }),
  product({
    slug: 'silk-charmeuse-blouse',
    name: 'Silk Charmeuse Blouse',
    category: 'women-shirting',
    gender: 'women',
    tier: 'ready-to-wear',
    price: 420,
    short: 'A relaxed blouse in liquid silk charmeuse.',
    description:
      'Cut with a dropped shoulder and a single button cuff, in a silk charmeuse with enough weight to fall cleanly rather than cling. Mother-of-pearl buttons.',
    fabric: '100% silk charmeuse.',
    care: 'Dry clean recommended. Cool iron on reverse.',
    sizes: RTW_SIZES,
    colors: COLOR_SETS.neutral,
    tags: [],
  }),
  product({
    slug: 'tailored-wool-trouser-women',
    name: 'Tailored Wool Trouser',
    category: 'women-tailoring',
    gender: 'women',
    tier: 'ready-to-wear',
    price: 560,
    short: 'A high-rise trouser cut from Super 120s wool.',
    description:
      'A wide, straight leg cut from Super 120s worsted wool, with a fishtail back and a clean waistband — no belt loops. Falls to a break at the ankle.',
    fabric: '100% Super 120s wool.',
    care: 'Dry clean only.',
    sizes: RTW_SIZES,
    colors: COLOR_SETS.evening,
    tags: [],
  }),
  product({
    slug: 'merino-crewneck-sweater',
    name: 'Merino Crewneck Sweater',
    category: 'women-knitwear',
    gender: 'women',
    tier: 'ready-to-wear',
    price: 340,
    short: 'A fully-fashioned crewneck in extra-fine merino.',
    description:
      'Knitted to shape rather than cut and sewn, in an extra-fine merino that sits close without clinging. A slightly cropped body, ribbed cuffs and hem.',
    fabric: '100% extra-fine merino wool.',
    care: 'Hand wash cold or dry clean. Dry flat.',
    sizes: RTW_SIZES,
    colors: COLOR_SETS.neutral,
    tags: ['New'],
    featured: true,
  }),
  product({
    slug: 'raw-silk-slip-dress',
    name: 'Raw Silk Slip Dress',
    category: 'women-shirting',
    gender: 'women',
    tier: 'ready-to-wear',
    price: 780,
    short: 'A bias-cut slip dress in raw silk noil.',
    description:
      'Cut on the bias from a raw silk noil with a dry, textured hand, this slip falls to mid-calf on a straight body. Adjustable straps, a single side seam.',
    fabric: '100% raw silk noil.',
    care: 'Dry clean only.',
    sizes: RTW_SIZES,
    colors: COLOR_SETS.warm,
    tags: [],
  }),
  product({
    slug: 'double-breasted-blazer-women',
    name: 'Double-Breasted Blazer',
    category: 'women-tailoring',
    gender: 'women',
    tier: 'ready-to-wear',
    price: 980,
    short: 'A soft-shouldered double-breasted blazer.',
    description:
      'Half-canvassed and soft in the shoulder, cut to sit open rather than buttoned. Peak lapels, horn buttons, a single back vent.',
    fabric: '100% wool twill.',
    care: 'Dry clean only.',
    sizes: RTW_SIZES,
    colors: COLOR_SETS.evening,
    tags: [],
  }),

  // ---- Men — Ready-to-wear ----
  product({
    slug: 'herringbone-wool-overcoat',
    name: 'Herringbone Wool Overcoat',
    category: 'men-coats',
    gender: 'men',
    tier: 'ready-to-wear',
    price: 2100,
    short: 'A full-canvas overcoat in a bold herringbone.',
    description:
      'Cut from a heavyweight herringbone woven in Huddersfield, full canvas construction with hand-padded lapels. Falls just below the knee.',
    fabric: '100% wool herringbone, Huddersfield, England.',
    care: 'Dry clean only. Brush after each wear.',
    sizes: RTW_SIZES,
    colors: COLOR_SETS.neutral,
    tags: ['New'],
    featured: true,
  }),
  product({
    slug: 'cotton-gabardine-trench',
    name: 'Cotton Gabardine Trench',
    category: 'men-coats',
    gender: 'men',
    tier: 'ready-to-wear',
    price: 1650,
    short: 'A single-breasted trench in dry-finished gabardine.',
    description:
      'A tighter, more architectural take on the trench: single-breasted, storm flap, no belt. Cut from a dry-finished cotton gabardine that holds its shape.',
    fabric: '100% cotton gabardine.',
    care: 'Dry clean recommended.',
    sizes: RTW_SIZES,
    colors: COLOR_SETS.warm,
    tags: [],
  }),
  product({
    slug: 'two-piece-wool-suit',
    name: 'Two-Piece Wool Suit',
    category: 'men-tailoring',
    gender: 'men',
    tier: 'ready-to-wear',
    price: 1780,
    short: 'A house-block two-piece in Super 130s wool.',
    description:
      'Our house block in a Super 130s wool with a soft, natural shoulder and a two-button front. Half-lined jacket, flat-front trouser with a slight taper.',
    fabric: '100% Super 130s wool.',
    care: 'Dry clean only.',
    sizes: RTW_SIZES,
    colors: COLOR_SETS.evening,
    tags: ['Limited'],
  }),
  product({
    slug: 'oxford-cotton-shirt',
    name: 'Oxford Cotton Shirt',
    category: 'men-shirting',
    gender: 'men',
    tier: 'ready-to-wear',
    price: 220,
    short: 'A button-down collar shirt in heavyweight oxford.',
    description:
      'A heavyweight oxford cloth cut with a soft button-down collar and a single chest pocket. Mother-of-pearl buttons, a slightly relaxed body.',
    fabric: '100% cotton oxford.',
    care: 'Machine wash cold. Warm iron.',
    sizes: RTW_SIZES,
    colors: COLOR_SETS.neutral,
    tags: [],
  }),
  product({
    slug: 'cashmere-vneck-sweater',
    name: 'Cashmere V-Neck Sweater',
    category: 'men-knitwear',
    gender: 'men',
    tier: 'ready-to-wear',
    price: 390,
    short: 'A fine-gauge V-neck in pure cashmere.',
    description:
      'Fully fashioned in a fine 12-gauge pure cashmere, cut close through the body with a set-in sleeve. Ribbed neck, cuffs and hem.',
    fabric: '100% cashmere.',
    care: 'Hand wash cold or dry clean. Dry flat.',
    sizes: RTW_SIZES,
    colors: COLOR_SETS.warm,
    tags: [],
  }),
  product({
    slug: 'flat-front-wool-trouser',
    name: 'Flat-Front Wool Trouser',
    category: 'men-tailoring',
    gender: 'men',
    tier: 'ready-to-wear',
    price: 460,
    short: 'A flat-front trouser cut from mid-weight wool twill.',
    description:
      'A clean, flat-front trouser with a straight leg and a slight taper to the ankle. Cut from a mid-weight wool twill that holds a crease well.',
    fabric: '100% wool twill.',
    care: 'Dry clean only.',
    sizes: RTW_SIZES,
    colors: COLOR_SETS.evening,
    tags: [],
  }),
  product({
    slug: 'linen-camp-shirt',
    name: 'Linen Camp Shirt',
    category: 'men-shirting',
    gender: 'men',
    tier: 'ready-to-wear',
    price: 260,
    short: 'A camp-collar shirt in washed European linen.',
    description:
      'A camp collar, a boxy body and a single chest pocket, cut from a washed European linen that softens with every wear.',
    fabric: '100% linen.',
    care: 'Machine wash cold. Iron warm, or leave it be.',
    sizes: RTW_SIZES,
    colors: COLOR_SETS.neutral,
    tags: ['New'],
  }),
  product({
    slug: 'printed-camp-shirt',
    name: 'Printed Camp Shirt',
    category: 'men-shirting',
    gender: 'men',
    tier: 'ready-to-wear',
    price: 240,
    short: 'A camp-collar shirt in a bold print, cut from mid-weight cotton twill.',
    description:
      'A notch camp collar and a straight, boxy body cut from a mid-weight cotton twill. Worn open over a plain tee or buttoned to the top — the print does the rest.',
    fabric: '100% cotton twill.',
    care: 'Machine wash cold. Warm iron.',
    sizes: RTW_SIZES,
    colors: [
      { name: 'Camo Print', hex: '#5C6E52' },
      { name: 'Paisley Print', hex: '#4A4A47' },
    ],
    tags: ['New'],
    featured: true,
    images: [
      'product-photos/printed-camp-shirt-camo.jpg',
      'product-photos/printed-camp-shirt-paisley.jpg',
      'product-photos/printed-camp-shirt-group.jpg',
    ],
  }),
  product({
    slug: 'textured-knit-polo',
    name: 'Textured Knit Polo',
    category: 'men-knitwear',
    gender: 'men',
    tier: 'ready-to-wear',
    price: 195,
    short: 'A slub-textured polo with a contrast collar and cuffs.',
    description:
      'Knitted from a slub cotton-blend yarn for a heathered, textured surface, finished with a contrast collar and rib cuffs. Cut for a relaxed, slightly boxy fit.',
    fabric: 'Cotton-blend slub knit.',
    care: 'Machine wash cold. Do not tumble dry.',
    sizes: RTW_SIZES,
    colors: [{ name: 'Rust', hex: '#A85C4A' }],
    tags: [],
    images: ['product-photos/textured-knit-polo-1.jpg'],
  }),

  // ---- Custom-Made ----
  product({
    slug: 'custom-two-piece-suit',
    name: 'Custom Two-Piece Suit',
    category: 'custom-made',
    gender: 'unisex',
    tier: 'custom',
    price: 2400,
    short: 'A house pattern adjusted to your proportions, from the cloth book.',
    description:
      'Start from our house block and choose your cloth from around 120 options. We adjust length, sleeve and waist suppression to your measurements, with one fitting before delivery. Six weeks, start to finish.',
    fabric: 'Choice of wool, cashmere or linen from the house cloth book.',
    care: 'Dry clean only.',
    sizes: MADE_TO_MEASURE,
    colors: COLOR_SETS.evening,
    tags: [],
    featured: true,
    imageCount: 2,
  }),
  product({
    slug: 'custom-overcoat',
    name: 'Custom Overcoat',
    category: 'custom-made',
    gender: 'unisex',
    tier: 'custom',
    price: 2100,
    short: 'An overcoat pattern adapted to your fit, from a house cloth book.',
    description:
      'Our overcoat block, adjusted to your shoulder, sleeve and length, in a cloth of your choosing. One fitting, six weeks to delivery.',
    fabric: 'Choice of wool flannel, herringbone or cashmere blend.',
    care: 'Dry clean only.',
    sizes: MADE_TO_MEASURE,
    colors: COLOR_SETS.neutral,
    tags: [],
    imageCount: 2,
  }),
  product({
    slug: 'custom-dress-shirt-trio',
    name: 'Custom Dress Shirt Trio',
    category: 'custom-made',
    gender: 'unisex',
    tier: 'custom',
    price: 560,
    short: 'Three made-to-measure shirts from a single fitting.',
    description:
      'Collar, cuff and body adjusted to your measurements, with a choice of poplin, oxford or twill. Three shirts from a single fitting, four weeks to delivery.',
    fabric: 'Choice of Egyptian cotton poplin, oxford or twill.',
    care: 'Machine wash cold. Warm iron.',
    sizes: MADE_TO_MEASURE,
    colors: COLOR_SETS.neutral,
    tags: [],
    imageCount: 2,
  }),

  // ---- Bespoke ----
  product({
    slug: 'bespoke-two-piece-suit',
    name: 'Bespoke Two-Piece Suit',
    category: 'bespoke',
    gender: 'unisex',
    tier: 'bespoke',
    price: 6800,
    short: 'Cut from nothing but your own measurements, across three fittings.',
    description:
      'No pattern, no size — thirty measurements taken by a cutter and a paper pattern that exists only for you. Full canvas construction, hand-finished buttonholes, three fittings across twelve weeks.',
    fabric: 'Any cloth from our full book — over 400 options from mills in Biella, Huddersfield and Kyoto.',
    care: 'Dry clean only. Alterations for the life of the garment are included.',
    sizes: MADE_TO_MEASURE,
    colors: COLOR_SETS.evening,
    tags: ['Bespoke'],
    featured: true,
    imageCount: 2,
  }),
  product({
    slug: 'bespoke-overcoat',
    name: 'Bespoke Overcoat',
    category: 'bespoke',
    gender: 'unisex',
    tier: 'bespoke',
    price: 5400,
    short: 'A fully bespoke overcoat, patterned from your measurements alone.',
    description:
      'Cut from a pattern made only for you, with a full canvas front and hand-set sleeves. Three fittings across the make, twelve weeks to delivery.',
    fabric: 'Any coating cloth from our full book.',
    care: 'Dry clean only. Alterations for the life of the garment are included.',
    sizes: MADE_TO_MEASURE,
    colors: COLOR_SETS.neutral,
    tags: ['Bespoke'],
    imageCount: 2,
  }),
  product({
    slug: 'bespoke-evening-tuxedo',
    name: 'Bespoke Evening Tuxedo',
    category: 'bespoke',
    gender: 'unisex',
    tier: 'bespoke',
    price: 8200,
    short: 'A fully bespoke tuxedo in barathea or midnight wool.',
    description:
      'Peak lapels faced in grosgrain silk, a paper pattern cut for you alone, and three fittings to get every line exact. Built for one occasion and every one after it.',
    fabric: 'Barathea or midnight-blue wool, silk grosgrain facings.',
    care: 'Dry clean only. Alterations for the life of the garment are included.',
    sizes: MADE_TO_MEASURE,
    colors: COLOR_SETS.evening,
    tags: ['Bespoke', 'Limited'],
    imageCount: 2,
  }),
  product({
    slug: 'beaded-lace-bridal-gown',
    name: 'Beaded Lace Bridal Gown',
    category: 'bespoke',
    gender: 'women',
    tier: 'bespoke',
    price: 7200,
    short: 'A hand-beaded mermaid gown with a high lace neckline and a detachable satin train.',
    description:
      'A fitted mermaid silhouette in hand-beaded lace, with a high illusion-lace neck and long sleeves. A detachable satin overskirt extends the train for the ceremony and lifts away for the reception. Pattern, beading and fit are cut for you alone across three fittings.',
    fabric: 'Hand-beaded lace, silk-satin overskirt.',
    care: 'Professional bridal preservation cleaning only. Alterations for the life of the garment are included.',
    sizes: MADE_TO_MEASURE,
    colors: [{ name: 'Ivory', hex: '#F5F1E8' }],
    tags: ['Bespoke'],
    featured: true,
    images: [
      'product-photos/beaded-lace-bridal-gown-1.jpg',
      'product-photos/beaded-lace-bridal-gown-2.jpg',
      'product-photos/beaded-lace-bridal-gown-3.jpg',
      'product-photos/beaded-lace-bridal-gown-4.jpg',
      'product-photos/beaded-lace-bridal-gown-5.jpg',
    ],
  }),
];

const STORES = [
  {
    name: 'Flagship Showroom',
    address: '48 Marlowe Street, London, W1S 2QY',
    hours: 'Tue–Sat, 10:00–18:00',
    phone: '+44 20 7946 0958',
    lat: 51.5115,
    lng: -0.1445,
  },
  {
    name: 'Downtown Showroom',
    address: '212 Grand Street, New York, NY 10013',
    hours: 'Mon–Fri, 09:00–17:00',
    phone: '+1 212 555 0148',
    lat: 40.7195,
    lng: -73.9977,
  },
  {
    name: 'Atelier — by appointment',
    address: '9 Rue des Tanneurs, Paris, 75004',
    hours: 'By appointment only',
    phone: '+33 1 42 96 03 21',
    lat: 48.8555,
    lng: 2.3565,
  },
];

const JOURNAL_ARTICLES = [
  {
    slug: 'how-to-read-a-cloth-book',
    title: 'How to read a cloth book',
    dek: 'Weight, weave and finish — what the numbers on a swatch actually tell you.',
    category: 'Craft',
    body: 'A cloth book looks like a reference document, but it rewards being read like one. Weight is given in grams per metre, weave determines drape as much as durability, and finish — the pressing and shearing done after weaving — changes how a cloth ages more than the fibre itself. Start with weight for the season, weave for the use, and finish last.',
  },
  {
    slug: 'the-case-for-fewer-better-things',
    title: 'The case for fewer, better things',
    dek: 'On buying less often, and why cost-per-wear is the only metric that matters.',
    category: 'Style',
    body: 'A well-made coat worn for fifteen years costs less per wear than a poorly made one replaced every second winter, even before accounting for the difference in how each one looks on year ten. We built this house around that arithmetic.',
  },
  {
    slug: 'caring-for-cashmere',
    title: 'Caring for cashmere',
    dek: 'Pilling is not a flaw. Here is how to keep a knit looking new for decades.',
    category: 'Care',
    body: 'Cashmere pills because the fibre is short and fine — that is also what makes it soft. Hand wash in cold water with a mild detergent, dry flat away from direct heat, and use a cashmere comb rather than a razor to remove pills. Rotate sweaters across a week rather than wearing the same one daily.',
  },
  {
    slug: 'what-a-fitting-actually-does',
    title: 'What a fitting actually does',
    dek: 'Inside the three fittings of a bespoke commission.',
    category: 'Craft',
    body: 'The first fitting, in basted canvas, looks unfinished on purpose — it is the only point where a cutter can see the garment before it is permanently assembled. The second corrects what the first revealed. The third is a formality, if the first two were done properly.',
  },
  {
    slug: 'dressing-for-a-decade-not-a-season',
    title: 'Dressing for a decade, not a season',
    dek: 'A short list of what tends to still look right ten years on.',
    category: 'Style',
    body: 'Trend cycles move faster than good cloth ages. A navy overcoat, a grey flannel trouser, a white oxford shirt — none of these will ever look dated, because they were never fashionable in the first place. They were just correct.',
  },
  {
    slug: 'shoe-care-for-people-who-hate-shoe-care',
    title: 'Shoe care for people who hate shoe care',
    dek: 'The five-minute routine that adds five years.',
    category: 'Care',
    body: 'A soft brush after every wear removes the surface dust that grinds into leather over time. Cream polish twice a month keeps the leather fed. Cedar shoe trees, inserted while the leather is still warm from wear, do more for shape than anything else on this list.',
  },
];

module.exports = {
  CATEGORIES,
  PRODUCTS,
  STORES,
  JOURNAL_ARTICLES,
};
